import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Download, FileText, ChevronRight, X, Clock, Target, CheckCircle } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface SubjectDetail {
  subjectName: string;
  topic: string;
  plannedMinutes: number;
  completedMinutes: number;
  remainingMinutes: number;
  progress: number;
  status: string;
}

interface StudyPlanReport {
  id: string;
  date: string;
  totalSubjects: number;
  totalPlannedMinutes: number;
  totalCompletedMinutes: number;
  overallProgress: number;
  subjectsDetails: SubjectDetail[];
}

const Reports: React.FC = () => {
  const [reports, setReports] = useState<StudyPlanReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState<StudyPlanReport | null>(null);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const res = await axios.get('/api/reports', {
        headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
      });
      setReports(res.data);
    } catch (error) {
      console.error('Error fetching reports:', error);
    } finally {
      setLoading(false);
    }
  };

  const formatDuration = (minutes: number): string => {
    if (!minutes) return '0 mins';
    const hrs = Math.floor(minutes / 60);
    const mins = Math.round(minutes % 60);
    if (hrs > 0 && mins > 0) return `${hrs} hr${hrs > 1 ? 's' : ''} ${mins} mins`;
    if (hrs > 0) return `${hrs} hr${hrs > 1 ? 's' : ''}`;
    return `${mins} mins`;
  };

  const downloadPDF = (report: StudyPlanReport) => {
    const doc = new jsPDF();
    const dateStr = new Date(report.date).toLocaleDateString('en-US', { 
      year: 'numeric', month: 'long', day: 'numeric' 
    });

    const userName = localStorage.getItem('user') ? JSON.parse(localStorage.getItem('user')!).name : 'Student';

    // Header
    doc.setFontSize(22);
    doc.setTextColor(33, 37, 41);
    doc.text('AI STUDY PLANNER', 14, 20);
    doc.setFontSize(16);
    doc.text('STUDY PLAN REPORT', 14, 30);
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Student Name: ${userName}`, 14, 45);
    doc.text(`Date: ${dateStr}`, 14, 52);

    // Summary Section
    doc.setFontSize(14);
    doc.setTextColor(33, 37, 41);
    doc.text('SUMMARY', 14, 65);
    doc.line(14, 67, 196, 67);

    doc.setFontSize(12);
    doc.text(`Total Subjects: ${report.totalSubjects}`, 14, 75);
    doc.text(`Total Planned Study Time: ${formatDuration(report.totalPlannedMinutes)}`, 14, 82);
    doc.text(`Total Completed Study Time: ${formatDuration(report.totalCompletedMinutes)}`, 14, 89);
    doc.text(`Overall Progress: ${report.overallProgress}%`, 14, 96);

    // Table Section
    doc.setFontSize(14);
    doc.text('SUBJECT-WISE REPORT', 14, 110);
    doc.line(14, 112, 196, 112);

    const tableData = report.subjectsDetails.map(sub => [
      sub.subjectName,
      sub.topic,
      formatDuration(sub.plannedMinutes),
      formatDuration(sub.completedMinutes),
      formatDuration(sub.remainingMinutes),
      `${sub.progress}%`,
      sub.status
    ]);

    autoTable(doc, {
      startY: 120,
      head: [['Subject', 'Topic', 'Planned', 'Actually Studied', 'Remaining', 'Progress', 'Status']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 10, cellPadding: 5 },
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY || 120;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by AI Study Planner', 14, finalY + 15);

    doc.save(`Study_Plan_Report_${dateStr.replace(/ /g, '_')}.pdf`);
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
        <div>
          <h2 className="text-2xl font-bold text-gray-800">Reports</h2>
          <p className="text-gray-500 text-sm mt-1">Track your study progress for each generated study plan.</p>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-20">
          <div className="animate-spin w-10 h-10 border-4 border-blue-600 border-t-transparent rounded-full mx-auto mb-4"></div>
          <p className="text-gray-500 font-medium">Loading reports...</p>
        </div>
      ) : reports.length === 0 ? (
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-16 text-center">
          <FileText size={48} className="mx-auto text-gray-300 mb-4" />
          <h3 className="text-xl font-bold text-gray-800 mb-2">No Reports Yet</h3>
          <p className="text-gray-500">Generate a study plan and start studying to see your reports here.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {reports.map((report) => (
            <div key={report.id} className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden flex flex-col hover:shadow-md transition">
              <div className="p-6 border-b border-gray-50">
                <div className="flex justify-between items-start mb-4">
                  <div className="bg-blue-50 text-blue-700 font-bold px-4 py-1.5 rounded-full text-sm">
                    {new Date(report.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                  </div>
                  <div className="text-right">
                    <span className="text-2xl font-black text-gray-800">{report.overallProgress}%</span>
                    <p className="text-xs text-gray-500 font-medium uppercase tracking-wider">Progress</p>
                  </div>
                </div>
                
                <div className="space-y-3">
                  <div className="flex items-center gap-3 text-gray-600">
                    <Target size={18} className="text-indigo-500" />
                    <span className="text-sm font-medium">Subjects: <strong className="text-gray-800">{report.totalSubjects}</strong></span>
                  </div>
                  <div className="flex items-center gap-3 text-gray-600">
                    <Clock size={18} className="text-orange-500" />
                    <span className="text-sm font-medium">Planned: <strong className="text-gray-800">{formatDuration(report.totalPlannedMinutes)}</strong></span>
                  </div>
                  <div className="flex items-center gap-3 text-gray-600">
                    <CheckCircle size={18} className="text-green-500" />
                    <span className="text-sm font-medium">Completed: <strong className="text-gray-800">{formatDuration(report.totalCompletedMinutes)}</strong></span>
                  </div>
                </div>
              </div>
              <div className="p-4 bg-gray-50 flex items-center justify-between gap-3 mt-auto">
                <button 
                  onClick={() => setSelectedReport(report)}
                  className="flex-1 bg-white border border-gray-200 text-gray-800 py-2.5 rounded-xl font-semibold text-sm hover:bg-gray-50 transition flex items-center justify-center gap-2"
                >
                  VIEW REPORT <ChevronRight size={16} />
                </button>
                <button 
                  onClick={() => downloadPDF(report)}
                  className="px-4 py-2.5 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition"
                  title="Download PDF"
                >
                  <Download size={18} />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Detailed Report Modal */}
      <AnimatePresence>
        {selectedReport && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/40 backdrop-blur-sm">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="bg-white rounded-3xl shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col"
            >
              <div className="p-6 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
                <div>
                  <h3 className="text-2xl font-bold text-gray-800">Study Plan Report</h3>
                  <p className="text-gray-500 mt-1">
                    {new Date(selectedReport.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                  </p>
                </div>
                <div className="flex items-center gap-4">
                  <button 
                    onClick={() => downloadPDF(selectedReport)}
                    className="hidden md:flex px-4 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition items-center gap-2 font-medium text-sm"
                  >
                    <Download size={16} /> Download PDF
                  </button>
                  <button 
                    onClick={() => setSelectedReport(null)}
                    className="p-2 bg-white text-gray-500 hover:text-gray-800 hover:bg-gray-100 rounded-full border border-gray-200 transition"
                  >
                    <X size={20} />
                  </button>
                </div>
              </div>

              <div className="p-6 overflow-y-auto custom-scrollbar">
                {/* Summary Cards */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                  <div className="bg-gray-50 rounded-2xl p-4 border border-gray-100">
                    <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Total Subjects</p>
                    <p className="text-2xl font-black text-gray-800">{selectedReport.totalSubjects}</p>
                  </div>
                  <div className="bg-orange-50 rounded-2xl p-4 border border-orange-100">
                    <p className="text-xs font-bold text-orange-600 uppercase tracking-wider mb-1">Planned Time</p>
                    <p className="text-xl font-black text-orange-900">{formatDuration(selectedReport.totalPlannedMinutes)}</p>
                  </div>
                  <div className="bg-green-50 rounded-2xl p-4 border border-green-100">
                    <p className="text-xs font-bold text-green-600 uppercase tracking-wider mb-1">Completed Time</p>
                    <p className="text-xl font-black text-green-900">{formatDuration(selectedReport.totalCompletedMinutes)}</p>
                  </div>
                  <div className="bg-blue-50 rounded-2xl p-4 border border-blue-100">
                    <p className="text-xs font-bold text-blue-600 uppercase tracking-wider mb-1">Overall Progress</p>
                    <p className="text-2xl font-black text-blue-900">{selectedReport.overallProgress}%</p>
                  </div>
                </div>

                <h4 className="text-lg font-bold text-gray-800 mb-4 border-b pb-2">Subject-wise Study Report</h4>
                
                {/* Desktop Table View */}
                <div className="hidden md:block overflow-hidden border border-gray-200 rounded-2xl">
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="bg-gray-50 border-b border-gray-200 text-sm">
                        <th className="p-4 font-bold text-gray-700">Subject</th>
                        <th className="p-4 font-bold text-gray-700">Topic</th>
                        <th className="p-4 font-bold text-gray-700">Planned</th>
                        <th className="p-4 font-bold text-gray-700">Actually Studied</th>
                        <th className="p-4 font-bold text-gray-700">Remaining</th>
                        <th className="p-4 font-bold text-gray-700">Progress</th>
                        <th className="p-4 font-bold text-gray-700">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                      {selectedReport.subjectsDetails.map((sub, idx) => (
                        <tr key={idx} className="hover:bg-gray-50/50 transition">
                          <td className="p-4 font-bold text-gray-800">{sub.subjectName}</td>
                          <td className="p-4 text-gray-600">{sub.topic}</td>
                          <td className="p-4 text-gray-600 font-medium">{formatDuration(sub.plannedMinutes)}</td>
                          <td className="p-4 text-gray-600 font-medium">{formatDuration(sub.completedMinutes)}</td>
                          <td className="p-4 text-gray-600 font-medium">{formatDuration(sub.remainingMinutes)}</td>
                          <td className="p-4">
                            <div className="flex items-center gap-2">
                              <div className="w-16 h-2 bg-gray-200 rounded-full overflow-hidden">
                                <div 
                                  className={`h-full rounded-full ${sub.progress === 100 ? 'bg-green-500' : 'bg-blue-500'}`}
                                  style={{ width: `${sub.progress}%` }}
                                ></div>
                              </div>
                              <span className="text-xs font-bold text-gray-700">{sub.progress}%</span>
                            </div>
                          </td>
                          <td className="p-4">
                            <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                              sub.status === 'Completed' ? 'bg-green-100 text-green-700' : 
                              sub.status === 'Partially Completed' ? 'bg-blue-100 text-blue-700' : 
                              'bg-gray-100 text-gray-600'
                            }`}>
                              {sub.status}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {/* Mobile Card View */}
                <div className="md:hidden space-y-4">
                  {selectedReport.subjectsDetails.map((sub, idx) => (
                    <div key={idx} className="bg-white border border-gray-100 rounded-2xl p-4 shadow-sm">
                      <div className="flex justify-between items-start mb-3">
                        <div>
                          <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Subject</p>
                          <p className="font-bold text-gray-800 text-lg">{sub.subjectName}</p>
                        </div>
                        <span className={`px-2.5 py-1 rounded-lg text-xs font-bold ${
                          sub.status === 'Completed' ? 'bg-green-100 text-green-700' : 
                          sub.status === 'Partially Completed' ? 'bg-blue-100 text-blue-700' : 
                          'bg-gray-100 text-gray-600'
                        }`}>
                          {sub.status}
                        </span>
                      </div>
                      <div className="mb-4">
                        <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Topic</p>
                        <p className="text-gray-700 bg-gray-50 px-3 py-2 rounded-xl text-sm border border-gray-100">{sub.topic}</p>
                      </div>
                      
                      <div className="grid grid-cols-2 gap-3 mb-4">
                        <div className="bg-gray-50 p-3 rounded-xl border border-gray-100">
                          <p className="text-xs text-gray-500 mb-1">Planned Time</p>
                          <p className="font-bold text-gray-800">{formatDuration(sub.plannedMinutes)}</p>
                        </div>
                        <div className="bg-gray-50 p-3 rounded-xl border border-gray-100">
                          <p className="text-xs text-gray-500 mb-1">Actual Time</p>
                          <p className="font-bold text-gray-800">{formatDuration(sub.completedMinutes)}</p>
                        </div>
                        <div className="bg-gray-50 p-3 rounded-xl border border-gray-100 col-span-2">
                          <p className="text-xs text-gray-500 mb-1">Remaining Time</p>
                          <p className="font-bold text-gray-800">{formatDuration(sub.remainingMinutes)}</p>
                        </div>
                      </div>

                      <div>
                        <div className="flex justify-between items-end mb-1">
                          <p className="text-xs font-bold text-gray-500 uppercase tracking-wider">Progress</p>
                          <span className="text-sm font-bold text-gray-800">{sub.progress}%</span>
                        </div>
                        <div className="w-full h-2.5 bg-gray-100 rounded-full overflow-hidden">
                          <div 
                            className={`h-full rounded-full ${sub.progress === 100 ? 'bg-green-500' : 'bg-blue-500'}`}
                            style={{ width: `${sub.progress}%` }}
                          ></div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default Reports;
